apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  labels:
    app: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  # nfs:
  #   server: IPOFNFSSERVER
  #   # Exported path of your NFS server dont forget to change the above line
  #   path: "/mydbdata"